// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcu4QvYqthcE5SeX13K93jNiSYNt0b5cw',
    appId: '1:813286173539:web:64f323d3280cb30b1f8156',
    messagingSenderId: '813286173539',
    projectId: 'todotoday-e611e',
    authDomain: 'todotoday-e611e.firebaseapp.com',
    databaseURL: 'https://todotoday-e611e-default-rtdb.firebaseio.com',
    storageBucket: 'todotoday-e611e.appspot.com',
    measurementId: 'G-JJ91Z6H39N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtIVj_P1GMiGhFIylwqGvWUemxokfQloE',
    appId: '1:813286173539:android:8f473521a528ea031f8156',
    messagingSenderId: '813286173539',
    projectId: 'todotoday-e611e',
    databaseURL: 'https://todotoday-e611e-default-rtdb.firebaseio.com',
    storageBucket: 'todotoday-e611e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV_Lv5dShhsA-R0I6IX8TEVyapsdJwSjo',
    appId: '1:813286173539:ios:943b26622d27241b1f8156',
    messagingSenderId: '813286173539',
    projectId: 'todotoday-e611e',
    databaseURL: 'https://todotoday-e611e-default-rtdb.firebaseio.com',
    storageBucket: 'todotoday-e611e.appspot.com',
    androidClientId: '813286173539-2biqh3ud42tj14sumc4utiu7tomi316p.apps.googleusercontent.com',
    iosClientId: '813286173539-eqdrltkl8hc6f1p91f6dn64iudj54tvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todotoday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV_Lv5dShhsA-R0I6IX8TEVyapsdJwSjo',
    appId: '1:813286173539:ios:943b26622d27241b1f8156',
    messagingSenderId: '813286173539',
    projectId: 'todotoday-e611e',
    databaseURL: 'https://todotoday-e611e-default-rtdb.firebaseio.com',
    storageBucket: 'todotoday-e611e.appspot.com',
    androidClientId: '813286173539-2biqh3ud42tj14sumc4utiu7tomi316p.apps.googleusercontent.com',
    iosClientId: '813286173539-eqdrltkl8hc6f1p91f6dn64iudj54tvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todotoday',
  );
}
